// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Template.SqlDataAccess;

#nullable disable

namespace Template.SqlDataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220607205139_Se agrega tabla Solicitud")]
    partial class SeagregatablaSolicitud
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Template.SqlDataAccess.Entities.ItemEntity", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Template.SqlDataAccess.Entities.PruebaEntity", b =>
                {
                    b.Property<Guid>("PruebaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("PruebaId");

                    b.ToTable("Pruebas");
                });

            modelBuilder.Entity("Template.SqlDataAccess.Entities.SolicitudEntity", b =>
                {
                    b.Property<Guid>("IdSolicitud")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Desactivado")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaModificacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdInterfaz")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdTipoConexionDestino")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdTipoConexionOrigen")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumeroRITM")
                        .HasColumnType("int");

                    b.Property<string>("UA")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UM")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdSolicitud");

                    b.ToTable("Solicitudes");
                });
#pragma warning restore 612, 618
        }
    }
}
